Continue on the development of features
Xhz0729/my-booking-app-repository pull request #5
Opened 2024-10-29 22:35 UTC by Xhz0729

This pull request introduces several new dependencies and features to the `client` package, including Google Maps integration, a booking widget, and additional functionality for handling photos in the `AddPlaceForm` component.

### New Dependencies:
* Added `@react-google-maps/api` to integrate Google Maps into the application. (`client/package-lock.json`, `client/package.json`) [[1]](diffhunk://#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR11) [[2]](diffhunk://#diff-1846122c2c83a486a3693f7966aa522c34cf489f674185c4da0d9221683fd81fR13)
* Included `@googlemaps/js-api-loader`, `@googlemaps/markerclusterer`, and other related packages to support Google Maps features. (`client/package-lock.json`) [[1]](diffhunk://#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR897-R912) [[2]](diffhunk://#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR1085-R1114) [[3]](diffhunk://#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR1400-R1405)
* Added `invariant` and `supercluster` for additional utility functions. (`client/package-lock.json`) [[1]](diffhunk://#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR3290-R3298) [[2]](diffhunk://#diff-925cb809ce77c7f7f7f8bbd7594593438fc006dc56bf432a624c47722a784d3dR5205-R5213)

### New Features:
* **Google Maps Integration:**
  * Created `MapComponent` to display a map based on the place's address. (`client/src/components/MapComponent.jsx`)
* **Booking Widget:**
  * Developed `BookingWidget` component to handle booking details and user interactions. (`client/src/components/BookingWidget.jsx`)

### Enhancements to `AddPlaceForm`:
* Added functionality to delete photos and select a main photo. (`client/src/components/AddPlaceForm.jsx`) [[1]](diffhunk://#diff-87673caf0852692332c6331de6e38c2126b80557c4043aeb200ce91e6dc5e16aR116-R135) [[2]](diffhunk://#diff-87673caf0852692332c6331de6e38c2126b80557c4043aeb200ce91e6dc5e16aL166-R249)
* Introduced a price field to the form. (`client/src/components/AddPlaceForm.jsx`) [[1]](diffhunk://#diff-87673caf0852692332c6331de6e38c2126b80557c4043aeb200ce91e6dc5e16aR21-R22) [[2]](diffhunk://#diff-87673caf0852692332c6331de6e38c2126b80557c4043aeb200ce91e6dc5e16aR346-R355)
* Updated layout and input handling for check-in, check-out times, and guest numbers. (`client/src/components/AddPlaceForm.jsx`)

### Routing Updates:
* Added routes for `HomePage` and `PlaceDetailsPage` in the `App` component. (`client/src/App.jsx`) [[1]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR4-R12) [[2]](diffhunk://#diff-51b002bf85fbd146b38871b89ba0d41c2bead37756295748c67206aac23ddc9aR24-R31)

2024-10-29 23:57 UTC, ericadev requested changes

2024-10-29 23:57 UTC, ericadev commented on client/src/components/MapComponent.jsx
> +        setCoordinates(response.data); // { lat: 29.9974362, lng: -98.0986204 }
Remove unnecessary comment

2024-10-30 00:08 UTC, Xhz0729 commented on client/src/components/MapComponent.jsx
> +        setCoordinates(response.data); // { lat: 29.9974362, lng: -98.0986204 }
> Remove unnecessary comment

Unnecessary comment being removed.

2024-10-30 00:09 UTC, ericadev approved these changes

2024-10-30 02:50 UTC, merged